from pathlib import Path
from typing import Optional


def generate_pdf_report(result: dict, contract_name: str = "contract") -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("Install fpdf2: pip install fpdf2")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, "Contract Analysis Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"File: {contract_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    risk_level = result.get("risk_level", "MEDIUM")
    score = result.get("overall_risk_score", 50)

    risk_colors = {"LOW": (34, 197, 94), "MEDIUM": (234, 179, 8), "HIGH": (239, 68, 68), "CRITICAL": (220, 38, 38)}
    color = risk_colors.get(risk_level, (100, 100, 100))

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, f"Risk Score: {score}/100 - {risk_level}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(50, 50, 50)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, result.get("summary", ""))
    pdf.ln(6)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    red_flags = result.get("red_flags", [])
    if red_flags:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(200, 30, 30)
        pdf.cell(0, 10, f"Red Flags ({len(red_flags)} found)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(50, 50, 50)
        pdf.ln(2)

        for i, flag in enumerate(red_flags, 1):
            sev = flag.get("severity", "MEDIUM")
            sev_color = risk_colors.get(sev, (100, 100, 100))
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*sev_color)
            pdf.cell(0, 7, f"#{i} [{sev}]", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(50, 50, 50)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, f"Clause: {flag.get('clause', 'N/A')}")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, f"Why: {flag.get('why_risky', 'N/A')}")
            pdf.set_text_color(30, 100, 200)
            pdf.multi_cell(0, 5, f"Tip: {flag.get('negotiation_tip', 'N/A')}")
            pdf.set_text_color(50, 50, 50)
            pdf.ln(3)

    watchpoints = result.get("key_watchpoints", [])
    if watchpoints:
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 10, "Key Watchpoints", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for w in watchpoints:
            pdf.cell(0, 7, f"- {w}", new_x="LMARGIN", new_y="NEXT")

    steps = result.get("next_steps", [])
    if steps:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Next Steps", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for s in steps:
            pdf.cell(0, 7, f"- {s}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, "Generated by contract-scanner (github.com/Mustadz0/contract-scanner)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "This report is for informational purposes only and does not constitute legal advice.", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
